cargo-features = ["edition2024"]

[workspace]
members = [".", "entity", "migration"]

[package]
name = "neuronek-cli"
version = "0.1.0"
edition = "2024"

[tasks]
build = { script = ["cargo", "build"] }
test = { script = ["cargo", "nextest", "run"] }
# cargo miri nextest run
test-miri = { script = ["cargo", "miri", "nextest", "run"] }
lint = { script = ["cargo", "clippy"] }
custom-task = { script = ["echo", "Hello, custom task!"] }

[dependencies]
async-std = "1.12.0"
miette = { version = "7.2.0", features = ["fancy", "serde", "syntect"] }
thiserror = "1.0.63"
sea-orm = { version = "1.0.0-rc.7", features = [ "sqlx-sqlite", "runtime-async-std-native-tls", "macros", "mock" ] }
clap = { version = "4.5.9", features = ["cargo", "derive", "env", "string", "unicode"] }
sea-orm-cli = {version = "1.0.0-rc.7"}
sea-orm-migration = "1.0.0-rc.7"
sea-migration = {path = "./migration"}
sea-entity = {path = "./entity"}
lazy_static = "1.5.0"
platform-dirs = "0.3.0"
chrono = "0.4.38"

[dev-dependencies]
cargo-make = "0.37.14"
cargo-nextest = "0.9.11"