cargo-features = ["edition2024"]

[workspace]
members = ["cli", "packages/nudb", "packages/nudb-migration"]

#[dev-dependencies]
#cargo-make = "0.37.14"
#cargo-nextest = "0.9.11"
#sea-orm-cli = { version = "1.0.0-rc.7" }