cargo-features = ["edition2024"]

[package]
name = "nudb"
version = "0.1.0"
edition = "2024"

[lib]
name = "nudb"
path = "src/lib.rs"

[dependencies]
sea-orm-cli = { version = "1.1.0-rc.1" }
chrono = "*"
serde = { version = "*" }
sea-orm = { version = "1.1.0-rc.1", features = [
    "sqlx-sqlite",
    "runtime-async-std-native-tls",
    "macros",
    "mock",
    "with-chrono",
] }
async-std = { version = "1", features = ["attributes", "tokio1"] }
nudb_migration = { path = "../nudb-migration" }