cargo-features = ["edition2024"]

[package]
name = "neudb"
version = "0.1.0"
edition = "2024"

[lib]
name = "neudb"
path = "src/lib.rs"

[dependencies]
sea-orm-cli = { version = "1.0.0-rc.7" }
chrono = "*"
sea-orm = { version = "1.0.0-rc.7", features = [
    "sqlx-sqlite",
    "runtime-async-std-native-tls",
    "macros",
    "mock",
    "with-chrono",
] }
[dependencies.sea-orm-migration]
version = "1.0.0-rc.7"
features = [
    "runtime-async-std-native-tls",
    "sqlx-sqlite",
    "with-chrono",
    "sea-orm-cli",
]
async-std = { version = "1", features = ["attributes", "tokio1"] }
nudb_migration = { path = "../nudb-migration" }