[package]
name = "nudb_migration"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "nudb_migration"
path = "src/lib.rs"

[dependencies]
async-std = { version = "1", features = ["attributes", "tokio1"] }
chrono = "*"
sea-orm = { version = "1.1.0-rc.1", features = ["sqlx-sqlite", "runtime-async-std-native-tls", "macros", "mock", "with-chrono"] }
openssl = { version = "0.10", features = ["vendored"] }

[dependencies.sea-orm-migration]
version = "1.1.0-rc.1"
features = [
    "runtime-async-std-native-tls",
    "sqlx-sqlite",
    "with-chrono",
    "sea-orm-cli"
]
